name: Site QA
on:
  workflow_dispatch:
  push:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # ⬇️ use install (creates package-lock.json)
      - run: npm install

      - run: npx playwright install --with-deps
      - run: npm run urls           # collects pages from https://rareskills.io/sitemap.xml
      - run: npm run scan           # runs the checks (desktop + mobile)

      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
